// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_cs_api.Models;

namespace dotnet_cs_api.Migrations
{
    [DbContext(typeof(csDbContext))]
    [Migration("20210729130650_db2")]
    partial class db2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("dotnet_cs_api.Models.TblOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("OrderStatus")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.ToTable("TblOrders");
                });

            modelBuilder.Entity("dotnet_cs_api.Models.TblOrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("TblOrderOrderId")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("TblOrderOrderId");

                    b.ToTable("TblOrderItems");
                });

            modelBuilder.Entity("dotnet_cs_api.Models.TblProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("TblOrderItemOrderItemId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("TblOrderItemOrderItemId");

                    b.ToTable("TblProducts");
                });

            modelBuilder.Entity("dotnet_cs_api.Models.TblOrderItem", b =>
                {
                    b.HasOne("dotnet_cs_api.Models.TblOrder", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("TblOrderOrderId");
                });

            modelBuilder.Entity("dotnet_cs_api.Models.TblProduct", b =>
                {
                    b.HasOne("dotnet_cs_api.Models.TblOrderItem", null)
                        .WithMany("Product")
                        .HasForeignKey("TblOrderItemOrderItemId");
                });

            modelBuilder.Entity("dotnet_cs_api.Models.TblOrder", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("dotnet_cs_api.Models.TblOrderItem", b =>
                {
                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
